export const bd_location = [
  {
    asn: "AS812",
    city: "Vancouver",
    phone: "604.800.801",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.0.1",
    languages: "en-CA,fr-CA",
    latitude: 49.2827,
    longitude: -123.1207,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "V6B",
    region: "British Columbia",
    region_code: "BC",
    timezone: "America/Vancouver",
    utc_offset: "-0700",
    version: "IPv4",
  },

  {
    asn: "AS5769",
    city: "Montreal",
    phone: "104.790.801",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "142.114.0.1",
    languages: "fr-CA,en-CA",
    latitude: 45.5017,
    longitude: -73.5673,
    network: "142.114.0.0/16",
    org: "Bell Canada",
    postal: "H1A",
    region: "Quebec",
    region_code: "QC",
    timezone: "America/Toronto",
    utc_offset: "-0500",
    version: "IPv4",
  },

  {
    asn: "AS1136",
    city: "Amsterdam",
    phone: "201.200.501",
    continent_code: "EU",
    country: "NL",
    country_area: 41543,
    country_calling_code: "+31",
    country_capital: "Amsterdam",
    country_code: "NL",
    country_code_iso3: "NLD",
    country_name: "Netherlands",
    country_population: 17590672,
    country_tld: ".nl",
    currency: "EUR",
    currency_name: "Euro",
    in_eu: true,
    ip: "145.0.0.1",
    languages: "nl-NL,en",
    latitude: 52.3676,
    longitude: 4.9041,
    network: "145.0.0.0/16",
    org: "KPN B.V.",
    postal: "1011",
    region: "North Holland",
    region_code: "NH",
    timezone: "Europe/Amsterdam",
    utc_offset: "+0200",
    version: "IPv4",
  },

  {
    asn: "AS812",
    city: "Burnaby",
    phone: "778.802.803",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.70.1",
    languages: "en-CA",
    latitude: 49.2488,
    longitude: -122.9805,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "V5A",
    region: "British Columbia",
    region_code: "BC",
    timezone: "America/Vancouver",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "Richmond",
    phone: "236.804.805",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.80.1",
    languages: "en-CA",
    latitude: 49.1666,
    longitude: -123.1336,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "V6X",
    region: "British Columbia",
    region_code: "BC",
    timezone: "America/Vancouver",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "Surrey",
    phone: "604.806.807",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.90.1",
    languages: "en-CA",
    latitude: 49.1044,
    longitude: -122.8011,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "V3T",
    region: "British Columbia",
    region_code: "BC",
    timezone: "America/Vancouver",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "Coquitlam",
    phone: "778.808.809",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.100.1",
    languages: "en-CA",
    latitude: 49.2838,
    longitude: -122.7932,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "V3B",
    region: "British Columbia",
    region_code: "BC",
    timezone: "America/Vancouver",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "Grande Prairie",
    phone: "780.700.701",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.10.1",
    languages: "en-CA",
    latitude: 55.1707,
    longitude: -118.7947,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "T8V",
    region: "Alberta",
    region_code: "AB",
    timezone: "America/Edmonton",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "Fort McMurray",
    phone: "587.702.703",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.20.1",
    languages: "en-CA",
    latitude: 56.7264,
    longitude: -111.379,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "T9H",
    region: "Alberta",
    region_code: "AB",
    timezone: "America/Edmonton",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "Peace River",
    phone: "825.704.705",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.30.1",
    languages: "en-CA",
    latitude: 56.2382,
    longitude: -117.2919,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "T8S",
    region: "Alberta",
    region_code: "AB",
    timezone: "America/Edmonton",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "High Level",
    phone: "780.706.707",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.40.1",
    languages: "en-CA",
    latitude: 58.5169,
    longitude: -117.1361,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "T0H",
    region: "Alberta",
    region_code: "AB",
    timezone: "America/Edmonton",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "Edmonton",
    phone: "587.708.709",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.50.1",
    languages: "en-CA",
    latitude: 53.5461,
    longitude: -113.4938,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "T5A",
    region: "Alberta",
    region_code: "AB",
    timezone: "America/Edmonton",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS812",
    city: "St. Albert",
    phone: "825.710.711",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.60.1",
    languages: "en-CA",
    latitude: 53.6305,
    longitude: -113.6256,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "T8N",
    region: "Alberta",
    region_code: "AB",
    timezone: "America/Edmonton",
    utc_offset: "-0700",
    version: "IPv4",
  },
  {
    asn: "AS852",
    city: "Lake Country",
    phone: "236.903.904",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "64.180.20.1",
    languages: "en-CA",
    latitude: 50.0513,
    longitude: -119.4143,
    network: "64.180.0.0/16",
    org: "TELUS Communications",
    postal: "V4V",
    region: "British Columbia",
    region_code: "BC",
    timezone: "America/Vancouver",
    utc_offset: "-0800",
    version: "IPv4",
  },
  {
  asn: "AS852",
  city: "West Kelowna",
  phone: "778.901.902",
  continent_code: "NA",
  country: "CA",
  country_area: 9984670,
  country_calling_code: "+1",
  country_capital: "Ottawa",
  country_code: "CA",
  country_code_iso3: "CAN",
  country_name: "Canada",
  country_population: 38008005,
  country_tld: ".ca",
  currency: "CAD",
  currency_name: "Canadian Dollar",
  in_eu: false,
  ip: "64.180.45.1",
  languages: "en-CA",
  latitude: 49.8625,
  longitude: -119.5830,
  network: "64.180.0.0/16",
  org: "TELUS Communications",
  postal: "V4T",
  region: "British Columbia",
  region_code: "BC",
  timezone: "America/Vancouver",
  utc_offset: "-0800",
  version: "IPv4",
}

];
